SELECT '&{BATCH_ID}' AS BATCH_ID_RECEIVED;

UPDATE PROJECT_SEMESTRUCTURED.BRONZE.PIPELINE_BATCH_CONTROL
SET
    CSV_ROWS = (
        SELECT COUNT(*)
        FROM PROJECT_SEMESTRUCTURED.BRONZE.CSV_RAW_CONTENT
        WHERE BATCH_ID = '&{BATCH_ID}'
    ),
    JSON_ROWS = (
        SELECT COUNT(*)
        FROM PROJECT_SEMESTRUCTURED.BRONZE.RAW_JSON_INGESTION
        WHERE BATCH_ID = '&{BATCH_ID}'
    ),
    XML_ROWS = (
        SELECT COUNT(*)
        FROM PROJECT_SEMESTRUCTURED.BRONZE.RAW_XML_INGESTION
        WHERE BATCH_ID = '&{BATCH_ID}'
    ),
    TOTAL_ROWS =
        (
            SELECT COUNT(*)
            FROM PROJECT_SEMESTRUCTURED.BRONZE.CSV_RAW_CONTENT
            WHERE BATCH_ID = '&{BATCH_ID}'
        )
        +
        (
            SELECT COUNT(*)
            FROM PROJECT_SEMESTRUCTURED.BRONZE.RAW_JSON_INGESTION
            WHERE BATCH_ID = '&{BATCH_ID}'
        )
        +
        (
            SELECT COUNT(*)
            FROM PROJECT_SEMESTRUCTURED.BRONZE.RAW_XML_INGESTION
            WHERE BATCH_ID = '&{BATCH_ID}'
        ),
    STATUS = 'INGESTED',
    UPDATED_AT = CURRENT_TIMESTAMP()
WHERE BATCH_ID = '&{BATCH_ID}';