
CREATE OR REPLACE STORAGE INTEGRATION AZ_INT_TEST 
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = AZURE
    ENABLED = TRUE 
    AZURE_TENANT_ID = '89f07acd-846c-4cd3-9530-5b09c9936fcb'
    STORAGE_ALLOWED_LOCATIONS = ( 'azure://adlssmartproject13prod.dfs.core.windows.net/raw') ;

ALTER STORAGE INTEGRATION AZ_INT_TEST 
  SET STORAGE_ALLOWED_LOCATIONS = ('azure://adlssmartproject13prod.blob.core.windows.net/raw');

DESCRIBE STORAGE INTEGRATION az_INT_TEST;

DESCRIBE STAGE AZURE_STAGE ;

CREATE OR REPLACE STAGE AZURE_STAGE
  STORAGE_INTEGRATION = AZ_INT_TEST
  URL = 'azure://adlssmartproject13prod.blob.core.windows.net/raw'
  ;--FILE_FORMAT = (TYPE = CSV); -- Cambia el formato según tus archivos

  LIST @PRUEBA_TECNICA.BRONZE.AZURE_STAGE  ;

--- CREAR INTEGRATION GIT 

CREATE OR REPLACE SECRET DEV_DB.DEV_SCHEMA.github_secret
  TYPE = PASSWORD
  USERNAME = 'oscarduque9713'
  PASSWORD = 'ghp_tu_token_de_github';


  CREATE OR REPLACE API INTEGRATION PROJECT_SEMESTRUCTURED.BRONZE.GITHUB_API_INT
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/tu-usuario')
  ALLOWED_AUTHENTICATION_SECRETS = (DEV_DB.DEV_SCHEMA.github_secret)
  ENABLED = TRUE;

CREATE OR REPLACE API INTEGRATION PROJECT_SEMESTRUCTURED.BRONZE.GITHUB_INT_SNE
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/oscarduque9713')
  ENABLED = TRUE;

CREATE GIT REPOSITORY PROJECT_SEMESTRUCTURED.BRONZE.Snwoflake_SME 
	ORIGIN = 'https://github.com/oscarduque9713/Snwoflake_SME' 
	API_INTEGRATION = 'GITHUB_PUBLIC_API_INTEGRATION';

SHOW GIT REPOSITORIES;

ALTER GIT REPOSITORY PROJECT_SEMESTRUCTURED.BRONZE.Snwoflake_SME FETCH;

SHOW GIT BRANCHES IN GIT REPOSITORY Snwoflake_SME;

ALTER GIT REPOSITORY PROJECT_SEMESTRUCTURED.BRONZE.Snwoflake_SME FETCH;

SHOW GIT BRANCHES IN PROJECT_SEMESTRUCTURED.BRONZE.SNWOFLAKE_SME;


EXECUTE IMMEDIATE FROM @PROJECT_SEMESTRUCTURED.BRONZE.SNWOFLAKE_SME/branches/Developer/SQL/0.Prep_Env.sql;

LIST @PROJECT_SEMESTRUCTURED.BRONZE.SNWOFLAKE_SME/branches/Developer/;