

USE ROLE DEVELOPER ;
USE WAREHOUSE PROJECT ;

INSERT INTO &DB_NAME.BRONZE.PIPELINE_BATCH_CONTROL (
    BATCH_ID,
    STATUS,
    START_TS
)
SELECT
    'BATCH_' || TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD_HH24MISS') AS BATCH_ID,
    'RUNNING' AS STATUS,
    CURRENT_TIMESTAMP() AS START_TS;