--- CREAR OBJETOS NECESARIOS
CREATE DATABASE IF NOT EXISTS PROJECT_SEMESTRUCTURED ;

CREATE SCHEMA IF NOT EXISTS PROJECT_SEMESTRUCTURED.BRONZE ;

CREATE STAGE IF NOT EXISTS PROJECT_SEMESTRUCTURED.BRONZE.RAW ;

--- LIST Y REMOVE FILES IF THEY ALREADY EXIST
LIST @PROJECT_SEMESTRUCTURED.BRONZE.RAW;

---REMOVE @PROJECT_SEMESTRUCTURED.BRONZE.RAW;

---- CREATE FILE FORMATS

-- CSV files are loaded as raw lines because the source may contain
-- unexpected columns
---- CREAR FILE FORMAT 
CREATE FILE FORMAT IF NOT EXISTS PROJECT_SEMESTRUCTURED.BRONZE.CSV 
    TYPE = 'CSV'
    FIELD_DELIMITER = NONE
    SKIP_HEADER = 0
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
;    


-- JSON and XML files are loaded as plain text first.
-- This avoids rejecting files with dirty content such as headers,
-- footers, comments, invalid roots or inconsistent nested structures.
CREATE FILE FORMAT IF NOT EXISTS PROJECT_SEMESTRUCTURED.BRONZE.SEMITRUCTURED_DATA
    TYPE = 'CSV'
    FIELD_DELIMITER = NONE        -- without cols
    RECORD_DELIMITER = '\n'      -- read every line like a row
    SKIP_HEADER = 0;

----- CREATE TABLES ON BRONZE SCHEMA ---------------------------------------------------------------------

--- CREAR TABLA BRONZE CSV
CREATE TABLE IF NOT EXISTS PROJECT_SEMESTRUCTURED.BRONZE.CSV_RAW_CONTENT(
RAW_CONTENT STRING,
FILE_NAME STRING,
FILE_ROW_NUMBER NUMBER,
BATCH_ID STRING
);

------ XML

CREATE TABLE IF NOT EXISTS PROJECT_SEMESTRUCTURED.BRONZE.RAW_XML_INGESTION (
    XML_CONTENT  STRING,
    FILE_NAME    STRING,
    FILE_ROW_NUMBER INTEGER,
    LOAD_DT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID STRING
);

-------- JSON

CREATE TABLE IF NOT EXISTS PROJECT_SEMESTRUCTURED.BRONZE.RAW_JSON_INGESTION (
    json_content STRING,
    FILE_NAME    STRING,
    FILE_ROW_NUMBER INTEGER,
    LOAD_DT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID STRING
);

----- TABLA DE REGISTER CONTROL
CREATE TABLE IF NOT EXISTS PROJECT_SEMESTRUCTURED.BRONZE.PIPELINE_BATCH_CONTROL (
    BATCH_ID STRING,
    STATUS STRING,
    CSV_ROWS NUMBER DEFAULT 0,
    JSON_ROWS NUMBER DEFAULT 0,
    XML_ROWS NUMBER DEFAULT 0,
    TOTAL_ROWS NUMBER DEFAULT 0,
    START_TS TIMESTAMP_NTZ,
    END_TS TIMESTAMP_NTZ,
    ERROR_MESSAGE STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


---- CREATE TABLES SILVER --------------------------------------------

create TABLE IF NOT EXISTS PROJECT_SEMESTRUCTURED.SILVER.DIM_CUSTOMERS (
	CUSTOMER_ID VARCHAR(300),
	CUSTOMER_NAME VARCHAR(300),
	EMAIL VARCHAR(300),
	SEGMENT VARCHAR(300),
	LOYALTY_TIER VARCHAR(300),
	SIGNUP_SOURCE VARCHAR(300),
	IS_ACTIVE VARCHAR(300)
);

create TABLE IF NOT EXISTS PROJECT_SEMESTRUCTURED.SILVER.DIM_ORDER (
	ORDER_ID VARCHAR(300),
	CUSTOMER_ID VARCHAR(300),
	ORDER_DATE DATE,
	ORDER_STATUS VARCHAR(300),
	CHANNEL VARCHAR(300)
);

create TABLE IF NOT EXISTS PROJECT_SEMESTRUCTURED.SILVER.DIM_PRODUCT (
	SKU VARCHAR(300),
	PRODUCT_NAME VARCHAR(300),
	CATEGORY VARCHAR(300),
	UNIT_PRICE FLOAT,
	CURRENCY VARCHAR(300),
	IS_ACTIVE VARCHAR(300)
);

create TABLE IF NOT EXISTS PROJECT_SEMESTRUCTURED.SILVER.DIM_PAYMENTS (
	PAYMENT_ID VARCHAR(300),
	ORDER_ID VARCHAR(300),
	PAYMENT_METHOD VARCHAR(300),
	AMOUNT FLOAT,
	CURRENCY VARCHAR(300),
	STATUS VARCHAR(300)
);


-- CREATE TABLES GOLD ------------------------------------------------------------

create TABLE IF NOT EXISTS PROJECT_SEMESTRUCTURED.GOLD.DIM_CUSTOMERS (
	CUSTOMER_ID VARCHAR(300),
	CUSTOMER_NAME VARCHAR(300),
	EMAIL VARCHAR(300),
	SEGMENT VARCHAR(300),
	LOYALTY_TIER VARCHAR(300),
	SIGNUP_SOURCE VARCHAR(300),
	IS_ACTIVE VARCHAR(300)
);

create TABLE IF NOT EXISTS PROJECT_SEMESTRUCTURED.GOLD.DIM_ORDER (
	ORDER_ID VARCHAR(300),
	ORDER_DATE DATE,
	ORDER_STATUS VARCHAR(300),
	CHANNEL VARCHAR(300)
);

create TABLE IF NOT EXISTS PROJECT_SEMESTRUCTURED.GOLD.DIM_PAYMENT (
	PAYMENT_ID VARCHAR(300),
	ORDER_ID VARCHAR(300),
	PAYMENT_METHOD VARCHAR(300),
	CURRENCY VARCHAR(300),
	STATUS VARCHAR(300)
);

create TABLE IF NOT EXISTS PROJECT_SEMESTRUCTURED.GOLD.DIM_PRODUCT (
	SKU VARCHAR(300),
	PRODUCT_NAME VARCHAR(300),
	CATEGORY VARCHAR(300),
	UNIT_PRICE FLOAT,
	CURRENCY VARCHAR(300),
	IS_ACTIVE VARCHAR(300)
);

create TABLE IF NOT EXISTS PROJECT_SEMESTRUCTURED.GOLD.FACT_ORDER_GAPS (
	ORDER_ID VARCHAR(300),
	CUSTOMER_ID VARCHAR(300),
	ORDER_DATE DATE,
	GAP_TYPE VARCHAR(14),
	PAYMENT_AMOUNT FLOAT
);

create TABLE IF NOT EXISTS PROJECT_SEMESTRUCTURED.GOLD.FACT_TRANSACTIONS (
	TRANSACTION_ID VARCHAR(300),
	ORDER_ID VARCHAR(300),
	ORDER_DATE DATE,
	CUSTOMER_ID VARCHAR(300),
	SKU VARCHAR(300),
	QUANTITY FLOAT,
	PAYMENT_AMOUNT FLOAT
);


---- TRUNCAR TABLES ALREADY EXISTS
TRUNCATE TABLE PROJECT_SEMESTRUCTURED.BRONZE.CSV_RAW_CONTENT;
TRUNCATE TABLE PROJECT_SEMESTRUCTURED.BRONZE.RAW_XML_INGESTION;
TRUNCATE TABLE PROJECT_SEMESTRUCTURED.BRONZE.RAW_JSON_INGESTION;
TRUNCATE TABLE PROJECT_SEMESTRUCTURED.SILVER.DIM_CUSTOMERS;
TRUNCATE TABLE PROJECT_SEMESTRUCTURED.SILVER.DIM_ORDER;
TRUNCATE TABLE PROJECT_SEMESTRUCTURED.SILVER.DIM_PRODUCT;
TRUNCATE TABLE PROJECT_SEMESTRUCTURED.SILVER.DIM_PAYMENTS;
TRUNCATE TABLE PROJECT_SEMESTRUCTURED.GOLD.DIM_CUSTOMERS;
TRUNCATE TABLE PROJECT_SEMESTRUCTURED.GOLD.DIM_ORDER;
TRUNCATE TABLE PROJECT_SEMESTRUCTURED.GOLD.DIM_PAYMENT;
TRUNCATE TABLE PROJECT_SEMESTRUCTURED.GOLD.DIM_PRODUCT; 
TRUNCATE TABLE PROJECT_SEMESTRUCTURED.GOLD.FACT_ORDER_GAPS;
TRUNCATE TABLE PROJECT_SEMESTRUCTURED.GOLD.FACT_TRANSACTIONS;
