
--- USE ROLE ACCOUNT ADMIN TO CREATE ROLE AND ASSING ROLE TO OUSER AD ACREATE THE WAREHOUSE 
USE ROLE ACCOUNTADMIN ;
USE WAREHOUSE COMPUTE_WH ;

---- CREATE ROLE 
CREATE ROLE IF NOT EXISTS DEVELOPER ;

--- ASSIGN ROLE TO THE USER
GRANT ROLE DEVELOPER TO USER oscarduque13;


-- Create resource monitor fro controllinh quotas
CREATE RESOURCE MONITOR IF NOT EXISTS RM_PROJECT
    WITH CREDIT_QUOTA = 10
    FREQUENCY = DAILY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO NOTIFY
        ON 95 PERCENT DO SUSPEND;

-- Create warehouse with auto suspend and resource monitor
CREATE WAREHOUSE IF NOT EXISTS PROJECT
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 10
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    RESOURCE_MONITOR = RM_PROJECT
;

-- GRANT ACCESS NEW WAREHOUSE TO THE NEW ROLE
GRANT USAGE ON WAREHOUSE PROJECT TO ROLE DEVELOPER;

----  CHANGE ROLE SYSADMIN
USE ROLE SYSADMIN ;

---- CREATE DATABASE
CREATE DATABASE IF NOT EXISTS &DB_NAME ;

--. GRANT PERMISSIONS TO THE ROLE DEVELOPER
GRANT USAGE ON DATABASE &DB_NAME TO ROLE DEVELOPER;

GRANT CREATE SCHEMA ON DATABASE &DB_NAME TO ROLE DEVELOPER;

GRANT CREATE STAGE ON FUTURE SCHEMAS 
IN DATABASE &DB_NAME 
TO ROLE DEVELOPER;

GRANT CREATE TABLE ON FUTURE SCHEMAS 
IN DATABASE &DB_NAME 
TO ROLE DEVELOPER;

--- USE NEW ROLE AND WAREHOUSE
USE ROLE DEVELOPER ;
USE WAREHOUSE PROJECT ;

--- CREAR OBJETOS NECESARIOS

CREATE SCHEMA IF NOT EXISTS &DB_NAME.BRONZE ;

CREATE STAGE IF NOT EXISTS &DB_NAME.BRONZE.RAW ;

CREATE SCHEMA IF NOT EXISTS &DB_NAME.SILVER ;

CREATE SCHEMA IF NOT EXISTS &DB_NAME.GOLD ;

--- LIST Y REMOVE FILES IF THEY ALREADY EXIST
LIST @&DB_NAME.BRONZE.RAW;

---REMOVE @&DB_NAME.BRONZE.RAW;

---- CREATE FILE FORMATS

-- CSV files are loaded as raw lines because the source may contain
-- unexpected columns
---- CREAR FILE FORMAT 
CREATE FILE FORMAT IF NOT EXISTS &DB_NAME.BRONZE.CSV 
    TYPE = 'CSV'
    FIELD_DELIMITER = NONE
    SKIP_HEADER = 0
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
;    


-- JSON and XML files are loaded as plain text first.
-- This avoids rejecting files with dirty content such as headers,
-- footers, comments, invalid roots or inconsistent nested structures.
CREATE FILE FORMAT IF NOT EXISTS &DB_NAME.BRONZE.SEMITRUCTURED_DATA
    TYPE = 'CSV'
    FIELD_DELIMITER = NONE        -- without cols
    RECORD_DELIMITER = '\n'      -- read every line like a row
    SKIP_HEADER = 0;

----- CREATE TABLES ON BRONZE SCHEMA ---------------------------------------------------------------------

--- CREAR TABLA BRONZE CSV
CREATE TABLE IF NOT EXISTS &DB_NAME.BRONZE.CSV_RAW_CONTENT(
RAW_CONTENT STRING,
FILE_NAME STRING,
FILE_ROW_NUMBER NUMBER,
BATCH_ID STRING
);

------ XML

CREATE TABLE IF NOT EXISTS &DB_NAME.BRONZE.RAW_XML_INGESTION (
    XML_CONTENT  STRING,
    FILE_NAME    STRING,
    FILE_ROW_NUMBER INTEGER,
    LOAD_DT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID STRING
);

-------- JSON

CREATE TABLE IF NOT EXISTS &DB_NAME.BRONZE.RAW_JSON_INGESTION (
    json_content STRING,
    FILE_NAME    STRING,
    FILE_ROW_NUMBER INTEGER,
    LOAD_DT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID STRING
);

----- TABLA DE REGISTER CONTROL
CREATE TABLE IF NOT EXISTS &DB_NAME.BRONZE.PIPELINE_BATCH_CONTROL (
    BATCH_ID STRING,
    STATUS STRING,
    CSV_ROWS NUMBER DEFAULT 0,
    JSON_ROWS NUMBER DEFAULT 0,
    XML_ROWS NUMBER DEFAULT 0,
    TOTAL_ROWS NUMBER DEFAULT 0,
    START_TS TIMESTAMP_NTZ,
    END_TS TIMESTAMP_NTZ,
    ERROR_MESSAGE STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


---- CREATE TABLES SILVER --------------------------------------------

create TABLE IF NOT EXISTS &DB_NAME.SILVER.DIM_CUSTOMERS (
	CUSTOMER_ID VARCHAR(300),
	CUSTOMER_NAME VARCHAR(300),
	EMAIL VARCHAR(300),
	SEGMENT VARCHAR(300),
	LOYALTY_TIER VARCHAR(300),
	SIGNUP_SOURCE VARCHAR(300),
	IS_ACTIVE VARCHAR(300)
);

create TABLE IF NOT EXISTS &DB_NAME.SILVER.DIM_ORDER (
	ORDER_ID VARCHAR(300),
	CUSTOMER_ID VARCHAR(300),
	ORDER_DATE DATE,
	ORDER_STATUS VARCHAR(300),
	CHANNEL VARCHAR(300)
);

create TABLE IF NOT EXISTS &DB_NAME.SILVER.DIM_PRODUCT (
	SKU VARCHAR(300),
	PRODUCT_NAME VARCHAR(300),
	CATEGORY VARCHAR(300),
	UNIT_PRICE FLOAT,
	CURRENCY VARCHAR(300),
	IS_ACTIVE VARCHAR(300)
);

create TABLE IF NOT EXISTS &DB_NAME.SILVER.DIM_PAYMENTS (
	PAYMENT_ID VARCHAR(300),
	ORDER_ID VARCHAR(300),
	PAYMENT_METHOD VARCHAR(300),
	AMOUNT FLOAT,
	CURRENCY VARCHAR(300),
	STATUS VARCHAR(300)
);


-- CREATE TABLES GOLD ------------------------------------------------------------

create TABLE IF NOT EXISTS &DB_NAME.GOLD.DIM_CUSTOMERS (
	CUSTOMER_ID VARCHAR(300),
	CUSTOMER_NAME VARCHAR(300),
	EMAIL VARCHAR(300),
	SEGMENT VARCHAR(300),
	LOYALTY_TIER VARCHAR(300),
	SIGNUP_SOURCE VARCHAR(300),
	IS_ACTIVE VARCHAR(300)
);

create TABLE IF NOT EXISTS &DB_NAME.GOLD.DIM_ORDER (
	ORDER_ID VARCHAR(300),
	ORDER_DATE DATE,
	ORDER_STATUS VARCHAR(300),
	CHANNEL VARCHAR(300)
);

create TABLE IF NOT EXISTS &DB_NAME.GOLD.DIM_PAYMENT (
	PAYMENT_ID VARCHAR(300),
	ORDER_ID VARCHAR(300),
	PAYMENT_METHOD VARCHAR(300),
	CURRENCY VARCHAR(300),
	STATUS VARCHAR(300)
);

create TABLE IF NOT EXISTS &DB_NAME.GOLD.DIM_PRODUCT (
	SKU VARCHAR(300),
	PRODUCT_NAME VARCHAR(300),
	CATEGORY VARCHAR(300),
	UNIT_PRICE FLOAT,
	CURRENCY VARCHAR(300),
	IS_ACTIVE VARCHAR(300)
);

create TABLE IF NOT EXISTS &DB_NAME.GOLD.FACT_ORDER_GAPS (
	ORDER_ID VARCHAR(300),
	CUSTOMER_ID VARCHAR(300),
	ORDER_DATE DATE,
	GAP_TYPE VARCHAR(14),
	PAYMENT_AMOUNT FLOAT
);

create TABLE IF NOT EXISTS &DB_NAME.GOLD.FACT_TRANSACTIONS (
	TRANSACTION_ID VARCHAR(300),
	ORDER_ID VARCHAR(300),
	ORDER_DATE DATE,
	CUSTOMER_ID VARCHAR(300),
	SKU VARCHAR(300),
	QUANTITY FLOAT,
	PAYMENT_AMOUNT FLOAT
);


---- TRUNCAR TABLES ALREADY EXISTS
/*TRUNCATE TABLE &DB_NAME.BRONZE.CSV_RAW_CONTENT;
TRUNCATE TABLE &DB_NAME.BRONZE.RAW_XML_INGESTION;
TRUNCATE TABLE &DB_NAME.BRONZE.RAW_JSON_INGESTION;
TRUNCATE TABLE &DB_NAME.SILVER.DIM_CUSTOMERS;
TRUNCATE TABLE &DB_NAME.SILVER.DIM_ORDER;
TRUNCATE TABLE &DB_NAME.SILVER.DIM_PRODUCT;
TRUNCATE TABLE &DB_NAME.SILVER.DIM_PAYMENTS;
TRUNCATE TABLE &DB_NAME.GOLD.DIM_CUSTOMERS;
TRUNCATE TABLE &DB_NAME.GOLD.DIM_ORDER;
TRUNCATE TABLE &DB_NAME.GOLD.DIM_PAYMENT;
TRUNCATE TABLE &DB_NAME.GOLD.DIM_PRODUCT; 
TRUNCATE TABLE &DB_NAME.GOLD.FACT_ORDER_GAPS;
TRUNCATE TABLE &DB_NAME.GOLD.FACT_TRANSACTIONS;*/
