USE ROLE DEVELOPER ;
USE WAREHOUSE PROJECT ;

--- LIST FILES 

LIST @PROJECT_SEMESTRUCTURED.BRONZE.RAW;

---- ingest csv


COPY INTO PROJECT_SEMESTRUCTURED.BRONZE.CSV_RAW_CONTENT
FROM (
    SELECT 
        $1 as raw_line,
        METADATA$FILENAME AS FILE_NAME,
        METADATA$FILE_ROW_NUMBER,
        '&{BATCH_ID}'
    FROM @PROJECT_SEMESTRUCTURED.BRONZE.RAW
    )
FILE_FORMAT = 'PROJECT_SEMESTRUCTURED.BRONZE.CSV'
PATTERN = '(?i).*\.csv.*';

--- Json and XML are loaded in text plane
------------- JSON

COPY INTO PROJECT_SEMESTRUCTURED.BRONZE.RAW_JSON_INGESTION 
FROM (
    SELECT $1,
    METADATA$FILENAME AS FILE_NAME,
    METADATA$FILE_ROW_NUMBER,
    CURRENT_TIMESTAMP(),
    '&{BATCH_ID}'
    FROM @PROJECT_SEMESTRUCTURED.BRONZE.RAW
)
FILE_FORMAT = (FORMAT_NAME = 'PROJECT_SEMESTRUCTURED.BRONZE.SEMITRUCTURED_DATA')
PATTERN = '.*\.json.*'
ON_ERROR = CONTINUE;


--- XML --------------------------

COPY INTO PROJECT_SEMESTRUCTURED.BRONZE.RAW_XML_INGESTION 
FROM (
    SELECT $1, 
    METADATA$FILENAME, 
    METADATA$File_row_number, 
    CURRENT_TIMESTAMP(),
    '&{BATCH_ID}'
    FROM @PROJECT_SEMESTRUCTURED.BRONZE.RAW
)
FILE_FORMAT = (FORMAT_NAME = 'PROJECT_SEMESTRUCTURED.BRONZE.SEMITRUCTURED_DATA')
PATTERN = '.*\.(xml|txt).*'
ON_ERROR = CONTINUE;


