USE ROLE DEVELOPER ;
USE WAREHOUSE PROJECT ;

UPDATE &DB_NAME.BRONZE.PIPELINE_BATCH_CONTROL
SET
    STATUS = 'SUCCESS',
    END_TS = CURRENT_TIMESTAMP(),
    UPDATED_AT = CURRENT_TIMESTAMP()
WHERE BATCH_ID = '&{BATCH_ID}';